version: 0.1

phases:
    install:
        commands:
            - pip install Pygments
            - wget https://github.com/spf13/hugo/releases/download/v0.18/hugo_0.18-64bit.deb
            - dpkg -i hugo_0.18-64bit.deb
    build:
        commands:
            - echo Build started
            - hugo
            - aws s3 sync public/ s3://blog.tryfinally.co.za/ --region us-east-1
            - echo "******** Uploading to S3 ********"

    post_build:
        commands:
            - echo Build completed on `date`
