version: 0.1

phases:
    install:
        commands:
            - pip install Pygments
            - wget https://github.com/gohugoio/hugo/releases/download/v0.21/hugo_0.21_Linux-64bit.deb
            - dpkg -i hugo_0.21_Linux-64bit.deb
    build:
        commands:
            - hugo
            - echo "******** Uploading to S3 ********"
            - aws s3 sync public/ s3://blog.tryfinally.co.za/ --region us-east-1
            - echo "******** Done! ********"

    post_build:
        commands:
            - echo Build completed on `date`
            - aws sns publish --topic-arn $SNS_TOPIC_ARN --subject 'AWS CodeBuild - Build Completed' --message 'The build has completed. For build details, go to https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logStream:group=/aws/codebuild/Blog in Amazon CloudWatch Logs.'
