baseurl = "https://d9ljg3fej692s.cloudfront.net"
languageCode = "en-us"
title = "Try ... Finally"
theme = "redlounge"
disqusShortname = "tryfinally"
[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"
[params]
    description = "Reports on my trails and tribulations"
    author = "Ivan du Toit"
    sidebartitle = "Try ... Finally"
    sidebartagline = "Reports on my trails and tribulations"
    sidebarphoto = "/img/profile.jpg"
[[menu.main]]
    Name = "Blog"
    url = "/posts"
[[menu.main]]
	Name = "Quotes"
	url = "/pages/quotes"
[[menu.main]]
	Name = "Laws"
	url = "/pages/laws"
[[menu.social]]
        pre = "<i class='fa fa-twitter'></i>"
    url = "https://www.twitter.com/anilihst"
    identifier = "twitter"
[[menu.social]]
        pre = "<i class='fa fa-github'></i>"
    url = "https://github.com/Ivan-du-toit"
    identifier = "Gitbub"
[[menu.social]]
        pre = "<i class='fa fa-linkedin'></i>"
    url = "https://za.linkedin.com/in/ivan-du-toit-33a93013"
    identifier = "LinkedIn"
[[menu.social]]
        pre = "<i class='fa fa-rss'></i>"
    url = "/index.xml"
    identifier = "RSS"
[[menu.footer]]
    name = "Blog"
    url = "/posts"
[[menu.footer]]
    name = "Quotes"
    url = "/pages/quotes"
